server:
  port: 8088
#  tomcat:
#    basedir: E:/Project/microservice/tomcat
#  servlet:
#    session:
#      storeDir: E:/Project/microservice/tomcat/session-trc
iot:
  service:
    static-url: http://dev.dm89.cn
    hot-url: http://zyh.dm89.cn:8000
    version: 0.0.12
    
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.1.10
    #host: 192.168.123.90
    port: 6379
    password: 
    database: 6
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/jjjy?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://192.168.123.90:3306/jjjy?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: pass
logging:
  #file: E:/Project/microservice/logs/svc-trc-dev.log
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    springfox.documentation: INFO
    cn.mingzhu.iot: DEBUG
  file : myLog.log